src/main/java/com/auction/usedauction/test/ApiTestController.java

Chore: 배포 자동화 테스트

---

scripts/gh_deploy.sh

Chore: 배포 자동화 deploy.sh 수정

---

scripts/gh_deploy.sh

Chore: deploy.sh 파일 이름 출력 수정

---

scripts/gh_deploy.sh

Chore: deploy.sh 파일 이름 출력 수정2

---

scripts/gh_deploy.sh

deploy.sh 파일 이름 출력 수정3

---

scripts/gh_deploy.sh

Chore: deploy.sh 파일 이름 출력 수정4

---

scripts/gh_deploy.sh

Chore: deploy.sh 파일 이름 출력 수정5

---

scripts/gh_deploy.sh

Chore: deploy.sh 파일 이름 출력 수정6

---

scripts/gh_deploy.sh

Chore: deploy.sh 파일 이름 출력 수정7

---

scripts/gh_deploy.sh

Chore: deploy.sh 배포 자동화 로그 테스트

Chore: deploy.sh 배포 자동화 로그 테스트

---

src/main/java/com/auction/usedauction/test/ApiTestController.java

Chore: 배포 자동화 정상 동작 테스트

---

.github/workflows/deploy.yaml
.gitignore
src/main/resources/application.yaml

배포될 때 application.yaml과 로컬에서의 application.yaml의 분리 가능 여부 체크

Chore: application.yaml 배포시 분리 테스트

---

.github/workflows/deploy.yaml

Chore: deploy.yaml RESOURCE_PATH 수정

Chore: deploy.yaml RESOURCE_PATH 수정

---

.github/workflows/deploy.yaml
src/main/resources/application-secret.yml

Chore: deploy.yaml env 제거 후 application.yml 파일이 잘 적용되는지 확인

Chore: deploy.yaml env 제거 후 테스트

---

.github/workflows/deploy.yaml
.gitignore

Chore: deploy.yaml env 제거 후 테스트2

Chore: deploy.yaml env 제거 후 테스트2

---

.github/workflows/deploy.yaml

Chore: deploy.yaml env 제거 후 테스트3

Chore: deploy.yaml env 제거 후 테스트3

---

src/main/resources/application.yaml

Chore: deploy.yaml env 제거 후 테스트4

Chore: deploy.yaml env 제거 후 테스트4

---

.github/workflows/deploy.yaml
src/main/resources/application-secret.yml

Chore: deploy.yaml env 제거 후 테스트5

Chore: deploy.yaml env 제거 후 테스트5

---

scripts/gh_deploy.sh

Chore: deploy.yaml env 제거 후 테스트7

Chore: deploy.yaml env 제거 후 테스트7

---

.github/workflows/deploy.yaml

Chore: deploy.yaml env 제거 후 테스트9

Chore: deploy.yaml env 제거 후 테스트9

---

.gitignore
src/main/resources/application-secret.yml

Chore: gitignore 테스트2

---

src/main/java/com/auction/usedauction/test/TestController.java

pull request test

---

.github/workflows/deploy.yaml
build.gradle
src/main/resources/application.yaml

Chore: db 연동 테스트

---

.github/workflows/deploy.yaml

Chore: db 연동 테스트2

---

.github/workflows/deploy.yaml

Chore: db 연동 테스트4

---

.github/workflows/deploy.yaml

Chore: db 연동 테스트5

---

.github/workflows/deploy.yaml

Chore: db 연동 테스트6

---

.github/workflows/deploy.yaml

Chore: db 연동 테스트7

---

.github/workflows/deploy.yaml

Chore: db 연동 테스트8

---

.github/workflows/deploy.yaml

Chore: db 연동 테스트9

---

.github/workflows/deploy.yaml

Chore: db 연동 테스트10

---

.github/workflows/deploy.yaml

Chore: db 연동 테스트11

---

.github/workflows/deploy.yaml

Chore: db 연동 테스트12

---

src/main/resources/application.yaml

Chore: db 연동 테스트13

---

.github/workflows/deploy.yaml

Chore: db 연동 테스트14

---

.github/workflows/deploy.yaml

Chore: db 연동 테스트15

---

.github/workflows/deploy.yaml

Chore: db 연동 테스트16

---

.github/workflows/deploy.yaml

Chore: db 연동 테스트17

---

.github/workflows/deploy.yaml

Chore: db 연동 테스트18

---

.gitignore
src/main/resources/application.yaml

Chore: db 연동 테스트19

---

.gitignore
src/main/resources/application.yaml

Chore: git ignore test

---

.github/workflows/deploy.yaml
build.gradle
src/main/java/com/auction/usedauction/UploadFIleDTO.java
src/main/java/com/auction/usedauction/config/AwsS3Config.java
src/main/java/com/auction/usedauction/exception/FileEmptyException.java
src/main/java/com/auction/usedauction/util/FileSubPath.java
src/main/java/com/auction/usedauction/util/S3FileUploader.java
src/main/resources/application.yaml
src/test/resources/application.yaml

Feat: S3 파일 업로드, 삭제 기능 추가

---

.github/workflows/deploy.yaml
build.gradle
src/main/java/com/auction/usedauction/config/AwsS3Config.java
src/main/java/com/auction/usedauction/util/FileSubPath.java
src/main/java/com/auction/usedauction/util/S3FileUploader.java
src/main/resources/application.yaml
src/test/java/com/auction/usedauction/S3MockingConfig.java
src/test/java/com/auction/usedauction/util/S3FileUploaderTest.java
src/test/resources/application.yaml

Test: S3 multipart 파일 업로드 기능 테스트 및 설정

Test: S3 multipart 파일 업로드 기능 테스트 및 설정

---

.github/workflows/deploy.yaml

Chore: Gradle Caching 이용해 build 속도 개선
Chore: S3 단일 build 파일 생성

Chore: deploy.yaml 변경

---

src/main/java/com/auction/usedauction/domain/Auction.java
src/main/java/com/auction/usedauction/domain/AuctionHistory.java
src/main/java/com/auction/usedauction/domain/AuctionStatus.java
src/main/java/com/auction/usedauction/domain/ChatRoom.java
src/main/java/com/auction/usedauction/domain/Product.java
src/main/java/com/auction/usedauction/domain/ProductStatus.java
src/main/resources/application.yaml

Refactor: DB 수정으로 인한 domain 수정

---

src/main/java/com/auction/usedauction/InitDBService.java
src/main/java/com/auction/usedauction/domain/Auction.java
src/main/java/com/auction/usedauction/domain/AuctionStatus.java
src/main/java/com/auction/usedauction/domain/Product.java
src/main/java/com/auction/usedauction/exception/error_code/AuctionErrorCode.java
src/main/java/com/auction/usedauction/repository/AuctionRepository.java
src/main/java/com/auction/usedauction/repository/auction_history/AuctionHistoryRepository.java
src/main/java/com/auction/usedauction/repository/auction_history/AuctionHistoryRepositoryCustomImpl.java
src/main/java/com/auction/usedauction/repository/product/ProductRepository.java
src/main/java/com/auction/usedauction/repository/product/ProductRepositoryCustom.java
src/main/java/com/auction/usedauction/repository/product/ProductRepositoryImpl.java
src/main/java/com/auction/usedauction/service/AuctionHistoryService.java
src/main/java/com/auction/usedauction/service/ProductService.java
src/main/java/com/auction/usedauction/service/dto/AuctionRegisterDTO.java
src/main/java/com/auction/usedauction/service/dto/MyPageAuctionHistoryPageContentRes.java
src/main/java/com/auction/usedauction/service/dto/MyPageAuctionHistoryPageRes.java
src/main/java/com/auction/usedauction/service/dto/MyPageProductPageContentRes.java
src/main/java/com/auction/usedauction/service/dto/MyPageProductPageRes.java
src/main/java/com/auction/usedauction/service/dto/ProductDetailInfoRes.java
src/main/java/com/auction/usedauction/service/dto/ProductPageContentRes.java
src/main/java/com/auction/usedauction/service/dto/ProductRegisterDTO.java
src/main/java/com/auction/usedauction/service/query/MyPageQueryService.java
src/main/java/com/auction/usedauction/util/AuctionProgressUtil.java
src/main/java/com/auction/usedauction/web/controller/MyPageController.java
src/main/java/com/auction/usedauction/web/controller/ProductController.java
src/test/java/com/auction/usedauction/repository/product/ProductRepositoryImplTest.java
src/test/java/com/auction/usedauction/service/ProductServiceTest.java
src/test/java/com/auction/usedauction/service/QuestionServiceTest.java
src/test/java/com/auction/usedauction/service/query/QuestionQueryServiceTest.java

ProductService, repository 수정 및 각종 dto 수정 및 생성

Refactor: 상품 CRUD 수정
